### ISSUE TITLE
Error page was displayed after registration of account

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#1]
Steps to replicate:
1. Navigate to the registration page.
2. Fill-out the form with correct details.
3. Select "Data Collector" as user role.
4. Click "Submit" button.

Actual result: An error page was displayed. Checked the database and has found that account details was saved. 

Expected result:
-Registration of account should succeed.
-A message should display saying that the account has been registered and is subject for approval.

![image](https://cloud.githubusercontent.com/assets/7791554/6120102/61319426-b10c-11e4-9c1e-34166f999a0c.png)

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.

**Comment by barbacenasmc** [comment]
Issue can be replicated again:
![image](https://cloud.githubusercontent.com/assets/7791554/6478829/bd2ad5e2-c275-11e4-83f0-95331d364212.png)

**Comment by xytram** [comment]
Wasn't able to replicate the issue

**Comment by barbacenasmc** [comment]
Issue was verified that it can no longer be replicated.
