### ISSUE TITLE
Edit Site: Site type does not display the previously selected option when the site was added

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#101]
Steps to replicate:
1. Navigate to the list of sites.
2. Click edit icon corresponding to a site.

Actual result: Site type does not display the previously selected option when the site was added.
Expected result: Site type should display the previously selected option when the site was added.

![image](https://cloud.githubusercontent.com/assets/7791554/7037698/ff44adb2-ddd8-11e4-9b39-750c73bad602.png)

**Comment by barbacenasmc** [comment]
Issue can still be replicated.

**Comment by ramoscharismarie** [comment]
Issue fix was verified.
