### ISSUE TITLE
Manage Responses: There was no confirmation message before the user can finally approve/disapprove the response

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#102]
Steps to replicate:
1. Navigate to list of responses.
2. Open an existing newly submitted response.
3. Click "Approve" button.
4. Open another existing newly submitted response.
5. Click "Disapprove" button.

Actual result: There was no confirmation message before the user can finally approve/disapprove the response
Expected result: There should confirmation message before the user can finally approve/disapprove the response

**Comment by Leirum** [comment]
Issue fix was already verified.

**Comment by barbacenasmc** [comment]
Issue fix was already verified. However, can we make the color of the approve button green?

![image](https://cloud.githubusercontent.com/assets/7791554/7310235/4a6daf12-ea5b-11e4-9d69-8318eb5c5bf9.png)
