### ISSUE TITLE
View Visual Report: Vulnerable Groups in Displacement Sites graph adds data from response 1 and 2

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#105]
Pre-condition:
-There should be no existing data for a site yet.
Steps to replicate:
1. Upload data for a specific site.
2. Using the same template and cycle, upload data for the same site again.
3. Approve both response.
4. Navigate to reports.
5. Select the site and view the visual graph report.

Actual result: Vulnerable Groups in Displacement Sites graph adds data from response 1 and 2
Expected result: Vulnerable Groups in Displacement Sites graph should only display the data of response 2

**Response 1 Data:**
![image](https://cloud.githubusercontent.com/assets/7791554/7038602/de5a8e92-dde6-11e4-9543-d629f94e1967.png)
**Response 2 Data:**
![image](https://cloud.githubusercontent.com/assets/7791554/7038606/e94feb6c-dde6-11e4-9154-8a9f1b53aeda.png)
**Graph:**
![image](https://cloud.githubusercontent.com/assets/7791554/7038591/b90b50e0-dde6-11e4-9f13-75033d3ad2e1.png)

**Comment by ramoscharismarie** [comment]
Issue fix was verified.
