### ISSUE TITLE
View Visual Report: IDP Sex Disaggregation per Site Type graph includes the data of all response from all sites

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#107]
Pre-condition:
-The following responses were existing:
**Site A (Response 1)**
Male - 40, Female - 60, Total - 100
**Site A (Response 2)**
Male - 80, Female - 120, Total - 200
**Site B (Response 1)**
Male - 40, Female - 60, Total - 100

*Note: All sites have the same site type*

**Steps to replicate:**
1. Navigate to reports.
2. Select Site A
3. Click Filter to view the visual report.

**Actual result:** 
IDP Sex Disaggregation per Site Type graph displays Male - 240, Female - 160, Total - 400
**Expected result:** 
IDP Sex Disaggregation per Site Type graph should display Male - 80, Female - 120, Total - 200

**Expected data to display:"
![image](https://cloud.githubusercontent.com/assets/7791554/7041423/b67caafc-de0b-11e4-9dbd-3b160577f6b8.png)

**Actual graph displayed:**
![image](https://cloud.githubusercontent.com/assets/7791554/7041436/ca706102-de0b-11e4-9b8c-7673eed0e8c7.png)

**Comment by ramoscharismarie** [comment]
Issue fix was verified.
