### ISSUE TITLE
Site Profile still displays an old response data

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#111]
Pre-condition:
-There should be two existing approved response for a site using the same cycle.
Steps to replicate:
1. Generate a PDF report for the site.

Actual result: Site profile still displays the data of the first uploaded data.
Expected result: Site profile should display the data of the latest response data.

![192 168 5 167 8000 admin pdfreports generate](https://cloud.githubusercontent.com/assets/7791554/7060235/ba9a82f4-deaf-11e4-8e01-d6fab40b0c95.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
