### ISSUE TITLE
Question ID displays different value in View Question Detail and Edit Question

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#114]
**Steps to replicate**
1. Navigate to Questions module.
2. Create new question.
3. View its details.
4. Edit Question.
5. Compare the information retrieve between the question details page and edit question.

**Actual Result**
Question ID in the page of question details and edit question are different.

![question id 1](https://cloud.githubusercontent.com/assets/9795882/7061506/83bec400-dec5-11e4-87dd-765c52f7076d.png)

![question id](https://cloud.githubusercontent.com/assets/9795882/7061508/85599f4c-dec5-11e4-9e57-338ccc82d6c6.png)

**Expected Result**
Question details page and edit question should retrieve the same data on each field provided.

**Comment by mgeronimo** [comment]
Sorry, I closed this via git commit.

**Comment by ramoscharismarie** [comment]
Issue fix was verified.
