### ISSUE TITLE
Add Question: "List/ Radio Button/ Select Multiple" Data Type Still Accepts One Input for the Answer Field

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#116]
**Steps to replicate**
1. Navigate to Questions module.
2. Create new question.
3. Fill out all fields.
4. Select "List/ Radio Button/ Select multiple" as data type.
5. Input one answer only in answer/ default answer field.
6. Click Save.

**Actual Result**
-Adding of new question succeeded

![aisle](https://cloud.githubusercontent.com/assets/9795882/7063783/20000f16-dedc-11e4-85f1-f8b112eaf426.png)

**Expected Result**
- Adding of new question should not succeed.
- It should have at least two answer.

**Comment by ramoscharismarie** [comment]
Invalid issue
