### ISSUE TITLE
Add Question: Text Data Type Accepts Number Inputs for Default Answer

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#118]
**Steps to replicate**
1. Navigate to Questions module.
2. Create new question.
3. Fill out all fields.
4. Select Text as data type.
5. Input numbers in default answer field.
6. Click Save.

**Actual Result**
Adding of new question still succeeded

**Expected Result**
- It should display a validation message indicating "Please select the right category for the question."
- If the user is going to use numbers for inputs in default answer, user should use, Number Data Type Instead.
- Adding of new question should not succeed
- It should display a validation message indicating that the input is invalid

**Comment by mgeronimo** [comment]
I think numbers as default answer for Text type is acceptable since it will be treated as text anyway.

**Comment by ramoscharismarie** [comment]
Invalid issue
