### ISSUE TITLE
Add Question: Number Data Type Accepts Special Characters as Valid Default Answer

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#119]
**Steps to replicate**
1. Navigate to Questions module.
2. Create new question.
3. Fill out all fields.
4. Select Number as data type.
5. Input special characters in default answer field.
6. Click Save.

**Actual Result**
-Adding of new question still succeeded

**Expected Result**
- Adding of new question should not succeed
- It should display a validation message that the input is invalid.
- Only numbers input should be valid as default answer

**Comment by mgeronimo** [comment]
See issue fix for #64. It also fixed the same problem

**Comment by adriancorpuz1** [comment]
Issue fix was already verified
