### ISSUE TITLE
Add Question: Answer disappears when form inputs was not saved due to invalid inputs

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#12]
Steps to replicate:
1. Navigate to add question page.
2. Select radio/list/checkbox as data type.
3. Fill-out the rest of the form except one required field.
4. Click Save.

Actual result: Page reloads and validation on the skipped required field was display. However, the answer field disappeared.
Expected result: Page should reload, show the necessary validation message and still display the answer field.

**Before**
![image](https://cloud.githubusercontent.com/assets/7791554/6323353/a3cd9ee0-bb63-11e4-93fc-f85a410805c1.png)

**After**
![image](https://cloud.githubusercontent.com/assets/7791554/6323354/a7ccdf60-bb63-11e4-9025-17da35668403.png)

**Comment by barbacenasmc** [comment]
Issue can still be replicated.

**Comment by xytram** [comment]
Unable to replicate issue

**Comment by barbacenasmc** [comment]
Issue was verified that it can no longer be replicated.
