### ISSUE TITLE
Add Question: "List/ Radio Button/ Select Multiple" Data Type, Only the First Option is Allowed as the Default Answer

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#121]
**Steps to replicate**
1. Navigate to Questions module.
2. Create new question.
3. Fill out all fields.
4. Select list/ as data type.
5. Input multiple answers in answer field and choose the second option as the default answer.
6. Click Save.

**Actual Result**
- only the first option can be chosen as the default answer.
- when the second, third option and so on, it displays a validation message indicating "Default answer should be one of the answers option"

![first](https://cloud.githubusercontent.com/assets/9795882/7063682/4e2506d6-dedb-11e4-86ee-a0c231017589.png)

![second](https://cloud.githubusercontent.com/assets/9795882/7063690/659b3f06-dedb-11e4-8331-a74d609f41ce.png)

![third](https://cloud.githubusercontent.com/assets/9795882/7063712/790d8724-dedb-11e4-85cd-43175b00366e.png)

**Expected Result**
User can choose any of the option given in the answers field.

**Comment by mgeronimo** [comment]
Possible answers must only be separated with semicolon (;) without spaces.

**Comment by Leirum** [comment]
Issue fix was already verified.

**Comment by Leirum** [comment]
Issue fix was already verified.
