### ISSUE TITLE
Add Question: Decimal Data Type Accepts Whole Number/ Letters/ Fraction/ Special Characters as A Valid Default Answer

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#123]
**Steps to Replicate**
1. Navigate to Questions module.
2. Create new question.
3. Fill out all fields.
4. Select decimal as data type.
5. Input whole number/ letters/ fraction/ special characters as default answer.
6. Click Save.

**Actual Result**
Adding of new question succeeded.

**Expected Result**
- Adding of new question should not succeed.
- It should display a validation message indicating "Please select the right category for the question."

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
