### ISSUE TITLE
User Can Create a Site without input on Site Type field

### ISSUE THREAD

**Issue by adriancorpuz1** [mgeronimo/IOM-DTM#127]
Steps to replicate
1. Log in as Manage Data Viewer
2. Navigate to add Site page 
3. Fill out all fields except Site Type
4. Click Save

Actual Result
User was able to create a site without selected on site type and data will be save.
Expected Result
User Should not be Added
A message should displayed on site type field

![image](https://cloud.githubusercontent.com/assets/11811605/7081242/a6a9184c-df71-11e4-9dc6-288abdde1a40.png)

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
