### ISSUE TITLE
View Visual Report: There is no prompt to tell the user that there is no available data for graphs yet

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#129]
Steps to replicate:
1. Create a cycle template that has questions from "Site Information from First Assessment" only.
2. Download the template on the mobile app.
3. Collect and upload data using the template.
4. On the web app, go to reports.
5. Generate a visual report for the site used in data collection.

Actual result: Graphs simply displays blank. There is no prompt to tell the user that there is no available data for graphs yet.
Expected result: Visual report should display that there are no data available for graphs yet.

![reports 4](https://cloud.githubusercontent.com/assets/7791554/7081515/e34a0ec4-df75-11e4-8329-83fa471e8f39.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
