### ISSUE TITLE
User Can Create a Site with an input of morethan 15 characters on Longtitude

### ISSUE THREAD

**Issue by adriancorpuz1** [mgeronimo/IOM-DTM#132]
Steps to replicate
1. Log in as Admin
2. Navigate to add site page
3. Fill out all fields with an input of morethan 15 characters on longtitude 
4. Click Save

Actual Result
User was able to create a site with morethan 15 characters on longgtitude
Expected Result
Site should not be added
A validation message displayed that the longtitude allows below 15 characters only 

![image](https://cloud.githubusercontent.com/assets/11811605/7082864/22e50216-df8d-11e4-910d-25a71ccd2bf2.png)

**Comment by barbacenasmc** [comment]
Both create site and edit site still allows more than 15 characters. Current maxlength on the forms is 45.

**Comment by adriancorpuz1** [comment]
Issue fix was already verified
