### ISSUE TITLE
User Can Create a Site with an input of morethan 15 characters on Latitude

### ISSUE THREAD

**Issue by adriancorpuz1** [mgeronimo/IOM-DTM#134]
Steps to replicate
1. Log in as Admin
2. Navigate to Manage Site page
3. Fill-out all fields with an input of morethan 15 characters on latitude
4. Click save button

Actual Result
User was able to create a site with morethan 15 characters on latitude
Expected Result
A new site should  not be added
A validation message displayed that the latitude allows exactly 15 characters and below only

![image](https://cloud.githubusercontent.com/assets/11811605/7112316/1d1dd284-e1fb-11e4-840c-225ab928784e.png)

**Comment by barbacenasmc** [comment]
Both create site and edit site still allows more than 15 characters. Current maxlength on the forms is 45.

**Comment by mgeronimo** [comment]
Please see new fix on issue #132

**Comment by adriancorpuz1** [comment]
Issue fix was already verified
