### ISSUE TITLE
User Can Delete a site that is already in use

### ISSUE THREAD

**Issue by adriancorpuz1** [mgeronimo/IOM-DTM#136]
Steps to replicate
1. Log in as Admin
2. Navigate to Manage Site
3. Click the delete icon corresponding to the site that is already used in data collection.

Actual Result:
-User was able to delete the already used  site
-Another impact would be the manage responses page will display an error page.

Expected Result:
-Site should not be deleted
-Validation message displayed that the already used site cannot be deleted.

![image](https://cloud.githubusercontent.com/assets/11811605/7112788/d1f183aa-e1ff-11e4-8a68-17a04f443da6.png)

**Comment by Leirum** [comment]
Issue can still be replicated.

**Comment by Leirum** [comment]
Issue fix was already verified.
