### ISSUE TITLE
User Can Create a Site thru Direct Link

### ISSUE THREAD

**Issue by adriancorpuz1** [mgeronimo/IOM-DTM#137]
Steps to replicate
1. Log in as Both Roles and Report Viewer
2. User can create a site thru direct link
http://dtm.solutionsresource.com/admin/site/add
3. Fill-out all the rest fields
4. Click Save

Actual Result
-User was able to access the manage data module
-User was  able to create a site

Expected Result
-User should not have the permission to access the page

 
![image](https://cloud.githubusercontent.com/assets/11811605/7129820/db3345e6-e297-11e4-856a-88923123deca.png)

![Uploading untitled1.JPG . . .]()

**Comment by Leirum** [comment]
Issue fix was already verified.
