### ISSUE TITLE
User Can Create Sub-Office thru Direct Link

### ISSUE THREAD

**Issue by adriancorpuz1** [mgeronimo/IOM-DTM#138]
Steps to replicate
1. Log in as Both Roles and Report Viewer
2. User can create sub-office thru direct link
http://dtm.solutionsresource.com/admin/sub-office/add
3. Fill-out all the rest fields
4. Click Save

Actual Result
-User was able to access the manage data module
-User was able to create a sub-office

Expected Result
-User should not have the permission to access the page

![image](https://cloud.githubusercontent.com/assets/11811605/7129884/fd5605cc-e298-11e4-8011-54fe1ad2450e.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
