### ISSUE TITLE
User Can Edit a Site thru Direct Link

### ISSUE THREAD

**Issue by adriancorpuz1** [mgeronimo/IOM-DTM#139]
Steps to replicate
1. Log in as Report Viewer
2. User can edit a site thru direct link
http://dtm.solutionsresource.com/admin/site/edit/7
3. Displayed an error page

Actual Rresult
-A validation displayed an error page

Expected Result
-User should not have the permission to access the page

![image](https://cloud.githubusercontent.com/assets/11811605/7129975/36b6de5c-e29b-11e4-8401-815c8081d803.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
