### ISSUE TITLE
User Can Edit Sub-Office thru Direct Link

### ISSUE THREAD

**Issue by adriancorpuz1** [mgeronimo/IOM-DTM#140]
Steps to replicate
1. Log in as Both Roles and Report Viewer
2. User can edit the sub-office thru direct link
http://dtm.solutionsresource.com/admin/sub-office/edit/1
3. Fill-out all the rest fields
4. Click Save

Actual Result
-User was able to access the manage data module
-User was able to select and edit the sub-offices

Expected Result
-User should not have the permission to access the page

![image](https://cloud.githubusercontent.com/assets/11811605/7130063/41cfc7c6-e29c-11e4-8c66-a049f3cf507e.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
