### ISSUE TITLE
Master Template with an Exisiting Child Template can be deleted.

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#144]
**Steps to replicate**
1. Navigate to "Emergencies" list.
2. Click the delete icon corresponding to an existing master template which already has an existing child template.
3. On the confirmation message, click "Delete".

**Actual Result**
Survey has been deleted successfully.

![10 1](https://cloud.githubusercontent.com/assets/9795882/7131511/f63315ae-e2b2-11e4-8edc-c696e0fe9c0c.png)

![10 2](https://cloud.githubusercontent.com/assets/9795882/7131535/12687aac-e2b3-11e4-811a-ef41ec8e1bf6.png)

![10 3](https://cloud.githubusercontent.com/assets/9795882/7131542/2271104e-e2b3-11e4-9fdb-b7d7712a03cc.png)

**Expected Result**
Deletion of master template should not succeed.

**Comment by mgeronimo** [comment]
Master template, even if it has a cycle template under it, can only be prevented from being deleted as long as at least one of its cycle (child) templates has a response.

**Comment by barbacenasmc** [comment]
This is not considered as issue. I'm changing the status to closed.
