### ISSUE TITLE
Add Emergency: User inputs still remained in all the fields after the adding of emergency have been cancelled.

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#147]
**Steps to replicate**
1. Navigate to Emergencies module.
2. Click the master template button on the upper right corner of the page. 
3. Fill out all required fields.
4. Click Save.
5. Click Cancel.
6. Click the master template button again.

**Actual Result**
All inputs still remained in all fields that was fill out by the user after the cancellation.

![29](https://cloud.githubusercontent.com/assets/9795882/7132059/23536bba-e2b8-11e4-87f9-6793c17fb77d.png)

**Expected Result**
All inputs should be removed from all the fields once the user clicks the add master template button again after the cancellation.

**Comment by ramoscharismarie** [comment]
Issue fix was verified.
