### ISSUE TITLE
All inputs were removed from its own fields after adding an emergency with an existing name.

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#148]
**Steps to replicate**
1. Navigate to Emergencies module.
2. Click the master template button on the upper right corner of the page.
3. Input an existing name in the emergency name field.
4. Fill out all fields.
5. Click Save.

**Actual Result**
It display a validation message for an existing emergency name but inputs in all fields were removed.

![30 1](https://cloud.githubusercontent.com/assets/9795882/7132152/429696f4-e2b9-11e4-836d-dedd8eaba025.png)

![30 2](https://cloud.githubusercontent.com/assets/9795882/7132153/42de3798-e2b9-11e4-9404-22f642e64442.png)

![30 3](https://cloud.githubusercontent.com/assets/9795882/7132175/6c62c1e2-e2b9-11e4-9829-c943090392f2.png)

**Expected Result**
- It should display a validation message indicating "Emergency name already exists."
- All inputs should still remain on its own field.

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated. Page returns the description while the site cannot be returned due to limitation of the form.
