### ISSUE TITLE
Add child template: Cycle name can be replicated.

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#150]
**Steps to replicate**
1. Navigate to Emergencies module.
2. Click the master template button on the upper right corner of the page.
3. Fill out all required fields in add emergency. 
4. Click Save.
5. Navigate to Edit Emergency and form designer frame.
6. Save emergency
7. Click the recently created emergency
8. Click the add cycle template button.
9. Add Cycle Template will pop-out but do not select a cycle no.
10. Click "add cycle template" button.
11. Delete few questions.
12. Save cycle as final
13. Repeat step 8-12

**Actual Result**
Cycle Name is now replicated

![36](https://cloud.githubusercontent.com/assets/9795882/7132869/c1fde360-e2bf-11e4-9c70-d402680f8385.png)

**Expected Result**
- Cycle name should be distinct.
- Select cycle no. must be a required field.
- User cannot add the cycle template without selecting a cycle no.

**Comment by barbacenasmc** [comment]
Error page now displays when tried to replicate this issue:
![whoops there was an error](https://cloud.githubusercontent.com/assets/7791554/7487074/a58ec6c0-f3e2-11e4-864f-e3e388401e8a.png)

**Comment by ramoscharismarie** [comment]
Issue fix was verified.
