### ISSUE TITLE
Creation of child template has been successfully added without selecting cycle number.

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#151]
**Steps to replicate**
1. Navigate to Emergencies module.
2. Click the master template button on the upper right corner of the page.
3. Fill out all required fields in add emergency. 
4. Click Save.
5. Navigate to Edit Emergency and form desinger
6. Save emergency
7. Click the recently created emergency
8. Click the add cycle template button.
9. Add Cycle Template will pop-out but do not select a cycle no. (EN 5 Cycle)
10. Click ""add cycle template"" button.
11. Delete few questions.
12. Save cycle as final
13. Repeat step 8
14. select cycle no. 1 (EN  5 Cycle 1)
15. Repeat step 11-12
16. Log in as report viewer in android app.
17. Click the emergency templates tab
18. Download EN 5 Cycle
19. Download EN 5 Cycle 1

**Actual Result**
- For not selecting the cycle number in the first creation of the child template, in creation of a second child, cycle #0 has been removed.
- Cycle 1 cannot be downloaded

**Expected Result**
- Cycle 0 must remain on the list of the cycle number.
- user should not be able to create a child template without selecting a child number.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
