### ISSUE TITLE
Changing the name of the master template doesn't have an effect on the child template's name.

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#154]
**Steps to replicate**
1. Create a Master Template
2. Create a child template 
3. Edit the Master Template name.
4. View its child template.

**Actual Result**
No changes have been made in cycle emergency details.

![41 1](https://cloud.githubusercontent.com/assets/9795882/7133262/0a2baba0-e2c4-11e4-82b9-6d5c5cf8aca8.png)

![41 2](https://cloud.githubusercontent.com/assets/9795882/7133273/24cf24fa-e2c4-11e4-8858-a3a476f0559e.png)

![41 3](https://cloud.githubusercontent.com/assets/9795882/7133280/3a41c324-e2c4-11e4-8212-901e7480f794.png)

**Expected Result**
Since the description of the child template will be based upon the name of the master template, it should be automatically updated once the name of the master template has been changed.

**Comment by barbacenasmc** [comment]
Issue no longer exists.
