### ISSUE TITLE
Updating Master Template name affects the downloading of emergency template in mobile app.

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#155]
**Steps to replicate**
1. Create a Master Template. (Master Template)
2. Create a child template. (Master Template cycle 0)
3. Edit the Master Template name. (Master Template Updated)
4. Create another child template. (Master Template Updated cycle 1)
5. Log in as report viewer in android app.
6. Click the emergencies template tab.
7. Download both child templates under master master template.

**Actual Result**
Master Template Updated Cycle 1 cannot be downloaded.

**Expected Result**
Both child template should be downloaded since it is under one master template and it has a chronological cycle number.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
