### ISSUE TITLE
Answered cycle templates can still be deleted.

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#156]
**Steps to replicate**
1. Log in as report viewer in android app.
2. Download an emergency template.
3. Fill out all fields then save.
4. Log in as admin in web app.
5. Navigate to emergencies module.
6. Look for the cycle template that has been answered in android app.
7. Delete the cycle template.

**Actual Result**
Cycle template has been successfully deleted.

**Expected Result**
Cycle template should not be able to delete.

**Comment by mgeronimo** [comment]
As of now, data collected must be uploaded first via the mobile app for the cycle to be prevented from being deleted.

**Comment by barbacenasmc** [comment]
This is not considered an issue. I'm changing the status to closed.
