### ISSUE TITLE
User Can Create a new Sub-Office using the name that already exists

### ISSUE THREAD

**Issue by adriancorpuz1** [mgeronimo/IOM-DTM#157]
Steps to replicate
1. Log in as Admin
2. Navigate to Manage Data page
3. Enter the Sub-Office name that already exists
3. Click Save

Actual Result
-User was able to add a new sub-office using the name that already use

Expected Result
-Addition of new sub-office should not succeed
-A validation message display that the sub-office name  is already exists

![image](https://cloud.githubusercontent.com/assets/11811605/7151357/53c72a4a-e35b-11e4-8ca8-4e40781d7e93.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
