### ISSUE TITLE
User Can Edit the Sub-Office without input on Sub-Office name

### ISSUE THREAD

**Issue by adriancorpuz1** [mgeronimo/IOM-DTM#158]
Steps to replicate
1. Log in as Admin
2. Navigate to Manage Data page
3. Select an existing sub-office and click the edit icon
4. Clear the content of sub-office name 
5. Click Save

Actual Result
-User was able to update sub-office without input on sub-office name 

Expected Result
-Updating of sub-office should not succeed
-A validation message indicate that the sub-office name is required

![image](https://cloud.githubusercontent.com/assets/11811605/7151532/0dd485de-e35e-11e4-8fdc-be19ad50687b.png)

![image](https://cloud.githubusercontent.com/assets/11811605/7151545/43e6b7d2-e35e-11e4-9a20-98403e6b23ca.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
