### ISSUE TITLE
User Can Edit the Sub-Office with Space only on Sub-Office name

### ISSUE THREAD

**Issue by adriancorpuz1** [mgeronimo/IOM-DTM#159]
Steps to replicate 
1. Log in as Admin
2. Navigate to Manage Data page
3. Select an existing sub-office and click the edit icon
4. Change the value of the sub-office name into white spaces
5. Click Save

Actual Result
-User was able to update sub-office without input on sub-office name

Expected Result
-Updating of sub-office should not succeed
-White spaces should be considered as null value
-A validation message indicating that the sub-office name is required

![image](https://cloud.githubusercontent.com/assets/11811605/7151658/79f4536e-e360-11e4-9e5d-f906c37e309f.png)

![image](https://cloud.githubusercontent.com/assets/11811605/7151674/cf181c0e-e360-11e4-9414-89e1901ec379.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
