### ISSUE TITLE
User Can Edit the Sub-Office without input all fields

### ISSUE THREAD

**Issue by adriancorpuz1** [mgeronimo/IOM-DTM#160]
Steps to replicate
1. Log in as Admin
2. Navigate to Manage Data page
3. Select the existing sub-office and click the edit icon
4. Clears the content of all fields
5. Click Save

Actual Result
-User was able to update the sub-office without input of all fields

Expected Result
-Updating of sub-office should not succeed
-A validation message indicating that the sub-office name is required

![image](https://cloud.githubusercontent.com/assets/11811605/7151793/97825e24-e362-11e4-8749-b4bf00eec6cf.png)

![image](https://cloud.githubusercontent.com/assets/11811605/7151802/ad603022-e362-11e4-8051-c913a5140f84.png)

**Comment by mgeronimo** [comment]
Issue cannot be replicated

**Comment by Leirum** [comment]
Issue cannot be replicated 
![screen shot 2015-04-16 at 2 56 36 pm](https://cloud.githubusercontent.com/assets/9795882/7175581/d42b3076-e448-11e4-94b2-b7556fd47f06.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
