### ISSUE TITLE
User Can Edit the Sub-Office and change its using the name that already exists

### ISSUE THREAD

**Issue by adriancorpuz1** [mgeronimo/IOM-DTM#161]
Steps to replicate 
1. Log in as Admin
2. Navigate to Manage Data page 
3. Select the existing sub-office and click the edit icon
4. Change the value of sub-office name that already exists
5. Click Save

Actual Result
-User was to able update the sub-office name even if its already exists
-A validation message indicating that the sub-office has been updated successfully

Expected Result
-Updating of sub-office should not succeed
-Sub-office name should serve as the unique identifier

![image](https://cloud.githubusercontent.com/assets/11811605/7151951/03f0bd9c-e365-11e4-8316-7ce8fb117f69.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
