### ISSUE TITLE
Data Collector Can Access the Emergencies Module thru Direct Link

### ISSUE THREAD

**Issue by adriancorpuz1** [mgeronimo/IOM-DTM#162]
Steps to replicate
1. Log in as Data Collector
2. Navigate to Emergencies Module thru direct link
http://dtm.solutionsresource.com/admin/surveys

Actual Result 
-User was able to access the emergencies module
-User was able to to add, edit and delete emergencies

Expected Result
-User should not have the permission to access the page

![image](https://cloud.githubusercontent.com/assets/11811605/7154375/03f8faac-e388-11e4-8020-1992a83f2691.png)

![image](https://cloud.githubusercontent.com/assets/11811605/7154415/8978d1fc-e388-11e4-8464-ddd3a6eda361.png)

![image](https://cloud.githubusercontent.com/assets/11811605/7154438/c00c7f70-e388-11e4-851a-1b5def34321b.png)

![image](https://cloud.githubusercontent.com/assets/11811605/7154470/030e7f62-e389-11e4-95c5-3d5fae3c305f.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
