### ISSUE TITLE
Data Collector Can Access the Question Module thru Direct Link

### ISSUE THREAD

**Issue by adriancorpuz1** [mgeronimo/IOM-DTM#163]
Steps to replicate
1. Log in as Data Collector
2. Navigate to Question Module thru direct  link
http://dtm.solutionsresource.com/admin/questions

Actual Result 
-User  was able to access the question module 
-User was able to add and edit questions 
-User was able to edit categories

Expected Result
-User should not have the permission to access the page

![image](https://cloud.githubusercontent.com/assets/11811605/7154648/ce89333e-e38a-11e4-830b-a77d418f0ea1.png)

![image](https://cloud.githubusercontent.com/assets/11811605/7154685/04e323d6-e38b-11e4-9705-ffa26b8d0b1e.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
