### ISSUE TITLE
Data Collector Can Access Create Question Module thru Direct Link

### ISSUE THREAD

**Issue by adriancorpuz1** [mgeronimo/IOM-DTM#164]
Steps to replicate
1. Log in as Data Collector
2. Navigate to Create Question module thru direct link
http://dtm.solutionsresource.com/admin/add-question

Actual Result
-User was able to access the Create Question 
-User was able to add a new question

Expected Result
-User should not have the permission to access the page

![image](https://cloud.githubusercontent.com/assets/11811605/7154905/16725854-e38d-11e4-9bd8-5b1a15509f68.png)

**Comment by mgeronimo** [comment]
Issue cannot be replicated.
