### ISSUE TITLE
Data Collector Displayed an Error page on Edit Question

### ISSUE THREAD

**Issue by adriancorpuz1** [mgeronimo/IOM-DTM#166]
Steps to replicate 
1. Log in as Data Collector
2. Navigate to Edit Question Module thru direct link
http://dtm.solutionsresource.com/admin/question/edit/185

Actual Result
-A validation displayed an error

Expected Result
-User should not have the permission to access  the page

![image](https://cloud.githubusercontent.com/assets/11811605/7155448/607af4c0-e391-11e4-8017-c4e37761b738.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
