### ISSUE TITLE
User Can Delete Sub-Office that is already Used in a User Registration

### ISSUE THREAD

**Issue by adriancorpuz1** [mgeronimo/IOM-DTM#167]
Steps to replicate 
1. Log in as Admin
2. Navigate to Manage Data page
3. Delete an existing Sub-Office that already in used in user registration

Actual Result
-User was able  to deleted the sub-office that already used in user registration
-A validation message displayed "Are yoou sure you want to delete this item? You cannot undo this action

Expected Result
-Deletion of sub office should not succeed.
-It should display a validation message indicating that the sub-office is already in used.

![image](https://cloud.githubusercontent.com/assets/11811605/7155813/2ceea11c-e394-11e4-9943-bb098b8cc068.png)

![image](https://cloud.githubusercontent.com/assets/11811605/7155827/4eb53e64-e394-11e4-9fdb-686fc779ff66.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
