### ISSUE TITLE
Test Question Validation: Warning Icon Doesn't Disable in the Fields with Valid Input Using Minus Sign Operation

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#168]
**Steps to replicate**
1. Log in as admin
2. Navigate to Emergencies module.
3. Add New Master Template.
4. In Form Designer Frame, select a question, add a validation and set the following inputs:
![screen shot 2015-04-16 at 2 15 59 pm](https://cloud.githubusercontent.com/assets/9795882/7175081/3bcf90f6-e443-11e4-9df6-b7c1446ae1d5.png)
8. Click Add.
9. Click Save Emergency.
10. Select the recently made Master Template
11. Create a child Template.
12. Download emergencies template on mobile app.
13. Collect data, and input valid answers on each fields with validation.

**Actual Result**
Warning icon in the fields with validation doesn't disable even the user input is valid.

![difference](https://cloud.githubusercontent.com/assets/9795882/7175116/c301565e-e443-11e4-8c37-163ef2c6f9b8.png)

**Expected Result**
Warning icon should be disabled in the fields with validation once the user input is valid.

**Comment by mgeronimo** [comment]
Issue should be logged on the mobile app repo.

**Comment by barbacenasmc** [comment]
Issue was already transferred to mobile app repo.
