### ISSUE TITLE
Test Question Validation: Warning Icon Doesn't Disable in the Fields with Valid Input Using Multiplication Operation

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#169]
**Steps to replicate**
1. Log in as admin
2. Navigate to Emergencies module.
3. Add New Master Template.
4. In Form Designer Frame, select a question, add a validation and set the following inputs:
![screen shot 2015-04-16 at 2 26 26 pm](https://cloud.githubusercontent.com/assets/9795882/7175217/9ff004ac-e444-11e4-8728-68de9630b9a7.png)
8. Click Add.
9. Click Save Emergency.
10. Select the recently made Master Template
11. Create a child Template.
12. Download emergencies template on mobile app.
13. Collect data, and input valid answers on each fields with validation.

**Actual Result**
Warning icon in the fields with validation doesn't disable even the user input is valid.

![product](https://cloud.githubusercontent.com/assets/9795882/7175226/b1b12f86-e444-11e4-83fc-c61b2a5f4721.png)

**Expected Result**
Warning icon should be disabled in the fields with validation once the user input is valid.

**Comment by mgeronimo** [comment]
Issue should be logged on the mobile app repo.

**Comment by barbacenasmc** [comment]
Issue was already transferred to mobile app repo.
