### ISSUE TITLE
Test Question Validation: Warning Icon Doesn't Disable in the Fields with Valid Input Using Division Operation

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#170]
**Steps to replicate**
1. Log in as admin
2. Navigate to Emergencies module.
3. Add New Master Template.
4. In Form Designer Frame, select a question, add a validation and set the following inputs:
![screen shot 2015-04-16 at 2 28 55 pm](https://cloud.githubusercontent.com/assets/9795882/7175248/f73ed7ec-e444-11e4-9b5d-3a04c12696e8.png)
8. Click Add.
9. Click Save Emergency.
10. Select the recently made Master Template
11. Create a child Template.
12. Download emergencies template on mobile app.
13. Collect data, and input valid answers on each fields with validation.

**Actual Result**
Warning icon in the fields with validation doesn't disable even the user input is valid.

![quotient](https://cloud.githubusercontent.com/assets/9795882/7175251/021cf176-e445-11e4-886e-f479285e03c8.png)

**Expected Result**
Warning icon should be disabled in the fields with validation once the user input is valid.

**Comment by mgeronimo** [comment]
Issue should be logged on the mobile app repo.

**Comment by barbacenasmc** [comment]
Issue was already transferred to mobile app repo.
