### ISSUE TITLE
Test Question Validation: "Unfortunately, IOM-DTM has stopped" when using a Modulo Operation

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#171]
**Steps to replicate**
1. Log in as admin
2. Navigate to Emergencies module.
3. Add New Master Template.
4. In Form Designer Frame, select a question, add a validation and set the following inputs:
![screen shot 2015-04-16 at 2 31 17 pm](https://cloud.githubusercontent.com/assets/9795882/7175282/521deb58-e445-11e4-9e0e-5756c2db90fa.png)
8. Click Add.
9. Click Save Emergency.
10. Select the recently made Master Template
11. Create a child Template.
12. Download emergencies template on mobile app.
13. Collect data, and input valid answers on each fields with validation.

**Actual Result**
When the user collects data from the emergency template using this kind of validation, the app will be closed automatically and displays "Unfortunately, IOM-DTM has stopped"

**Expected Result**
- IOM-DTM mobile app should be working properly using modulo operation.
- Warning icon should be enabled when the user input is invalid.
- Warning icon should be disabled when the user input is valid.

**Comment by mgeronimo** [comment]
Issue should be logged on the mobile app repo.

**Comment by barbacenasmc** [comment]
Issue was already transferred to mobile app repo.
