### ISSUE TITLE
Date created of master template duplicate was incorrect

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#172]
Steps to replicate:
1. Navigate to the list of emergencies.
2. Duplicate an existing master template.

Actual result: Current time was around 8:48 but date created was '2015-04-24 00:48:52'
Expected result: Date created of master template duplicate should be the actual date and time when it was duplicated.

![image](https://cloud.githubusercontent.com/assets/7791554/7310468/088841e4-ea5f-11e4-8802-76bcd4c6b388.png)

**Comment by ramoscharismarie** [comment]
Issue fix was verified.
