### ISSUE TITLE
Edit Master Template: Question from a non-existing cluster could not be added to the template

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#180]
Steps to replicate:
1. Create a new master template with group of questions for 1 cluster only.
2. Edit the template and try to add another question which do not belong to the existing cluster.

Actual result: Question could not be added to the template. When clicked "Add Question" button, nothing happens.
Expected result: Question should be added to the template.

![image](https://cloud.githubusercontent.com/assets/7791554/7486619/64ed6ae8-f3da-11e4-880c-2767dd7bbfe7.png)

![image](https://cloud.githubusercontent.com/assets/7791554/7486645/be08d860-f3da-11e4-9fca-fee3ff3dcb00.png)

**Comment by ramoscharismarie** [comment]
Issue fix was verified.
