### ISSUE TITLE
Edit Template: Validation messages display on emergency name and description field when user adds questions

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#181]
Steps to replicate:

1. Edit an existing master template.
2. Add another question.

Actual result: Validation messages display on emergency name and description field
Expected result: Validation messages should not display on emergency name and description field.

![image](https://cloud.githubusercontent.com/assets/7791554/7488724/9a55c286-f400-11e4-8607-4fd39fe22d21.png)

**Comment by ramoscharismarie** [comment]
Issue fix was verfied.
