### ISSUE TITLE
Associated sites were not displayed on when viewed or edited master template

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#183]
Steps to replicate:

1. View an existing master template.
2. Observe if associated sites are displayed on any part of the page.
3. Edit the master template.
4. Observe if associated sites are displayed on any part of the page.

Actual result: Associated sites were not displayed when viewed or edited master template
Expected result: Associated sites should displayed when viewed or edited master template

**Comment by ramoscharismarie** [comment]
Issue fix was verified.
