### ISSUE TITLE
Update Site: Williamson Forges Cannot be Updated.

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#184]
**Steps to replicate**
1. Navigate to Manage Data.
2. Edit the Williamson Forges site.
3. Don't write any changes and click Save.

**Actual Result**
- disabled fields for longitude and latitude are said to be required fields, yet the user is not allowed to input.

**Question**
How does the user add the site without an input on longitude and latitude fields even both of these are required fields?

![8](https://cloud.githubusercontent.com/assets/9795882/7793140/2fcc0d7a-02ed-11e5-9013-1fc958b8d9b7.png)

**Expected Result**
- User shouldn't be able to add a site without inputs on required fields.
- It should display a validation message indicating "Site has been successfully updated"

**Comment by ramoscharismarie** [comment]
Issue fix was verified
