### ISSUE TITLE
Misspelled label and Inconsistent field for Select Operation of Validation

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#186]
**Steps to Replicate**
1. Navigate to Emergencies tab.
2. Create Master Template.
3. Select an Question and add Validation.

**Actual Result**
- Misspelled label for Select Operation
- Composed of different fields for selecting validation operation.
   - First field is in drop down list.
   - Second field is in text field.

![4](https://cloud.githubusercontent.com/assets/9795882/7793925/c41c2bf4-02f7-11e5-9832-c69d1b32f902.png)

**Expected Result**
- Validation operation field should be labeled as "Select Operations"
- Select Operations should be in a drop down lists.

**Comment by ramoscharismarie** [comment]
Issue fix was verified.
