### ISSUE TITLE
Disapproval of response without a comment was successful

### ISSUE THREAD

**Issue by maarahoy** [mgeronimo/IOM-DTM#191]
Steps to replicate:

1. Navigate to Responses
2. Click a survey name
3. Click disapprove response

Actual result:  Disapproval of response without a comment was successful

Expected result:  Validation message should appear. Disapproval of response should not succeed.

![disapprove-without-comment](https://cloud.githubusercontent.com/assets/12744684/8714868/a8d7f4da-2bac-11e5-838e-79b80399ca83.png)

![disapprove-response-nocomment](https://cloud.githubusercontent.com/assets/12744684/8714892/ffd1e516-2bac-11e5-983c-61a626724a72.png)

![disapprove-nocomment-emailnotif](https://cloud.githubusercontent.com/assets/12744684/8714870/b79bcb4a-2bac-11e5-8b21-f823f90f0bf8.png)

**Comment by mgeronimo** [comment]
Fixed issue. Please see commit no. 4672c0a89ce2bfd97d413c6d0160bd0a6b959cd5.

**Comment by ramoscharismarie** [comment]
Issue fix was verified.
