### ISSUE TITLE
Disapprove response: Disapproval of response still successful without a comment

### ISSUE THREAD

**Issue by ramoscharismarie** [mgeronimo/IOM-DTM#192]
Steps to replicate:
1. Navigate to responses.
2. Click a pending response.
3. Click the disapprove response button.

Actual result:
- Disapproval of response without comment still successful

![dtm-disapproval-no-comment](https://cloud.githubusercontent.com/assets/12993604/8819034/c1b906f6-307a-11e5-9b34-64f5169cffde.PNG)
![dtm-disapproval-no-comment-successful](https://cloud.githubusercontent.com/assets/12993604/8819035/c1bf40c0-307a-11e5-8729-4c67746b2ad6.PNG)

Expected result:
- Disapproval must not be successful without a comment from the admin.

**Comment by mgeronimo** [comment]
Fixed issue. See commit no: 4672c0a89ce2bfd97d413c6d0160bd0a6b959cd5.

**Comment by ramoscharismarie** [comment]
Issue fix was verified.
