### ISSUE TITLE
Disapproved response and site was duplicated after downloading a disapproved response

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#193]
Pre-condition:
- Send a response for a specific site using the mobile app.
- As admin, disapprove the response.
- The site used for submission of the response still exists.
Steps to replicate:

1. Using the mobile app, download the disapproved response.
2. Tap "Collect Data" and choose "Use Disapproved Response."
3. Observe the number of items listed for the previously downloaded disapproved response.
4. Go to "Manage Downloaded Data" and go to "Sites" tab.
5. Look for the site that was used previously.

Actual result: Disapproved response and site was duplicated

Expected result: There should only be 1 disapproved response and 1 site that exists on the device.

Note: Mobile dev told that this is an API issue that's why it was logged here.
![screenshot_2015-07-27-09-27-22](https://cloud.githubusercontent.com/assets/7791554/8897169/bb0973d8-3442-11e5-969e-2d471dce985f.png)
![screenshot_2015-07-27-09-27-33](https://cloud.githubusercontent.com/assets/7791554/8897170/bb0a46c8-3442-11e5-9314-052758680dfd.png)

**Comment by ramoscharismarie** [comment]
Issue fix verified.
