### ISSUE TITLE
Add Survey: Newly added question cannot be retrieved

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#25]
Steps to replicate:
1. Add a new question.
2. Go to add survey form.
3. Click "Add Element".
4. Search for the previously added question.

Actual result: Newly added question cannot be retrieved.
Expected result: The question should be retrievable on the add questions form.

![image](https://cloud.githubusercontent.com/assets/7791554/6498952/c011d036-c32d-11e4-830d-85a83549d82a.png)

**Comment by xytram** [comment]
Cannot replicate issue in build # https://github.com/mgeronimo/IOM-DTM/commit/f4e76f38804da4f61b5c2029a46f670656c1551c

**Comment by barbacenasmc** [comment]
Issue was verified that it can no longer be replicated.
