### ISSUE TITLE
Edit question page does not show if a question is core or annex

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#29]
Steps to replicate:
1. Navigate to the list of questions.
2. Click edit icon corresponding to a question.

Actual result: Edit question page does not show if a question is core or annex
Expected result: There should be a disabled field showing the detail of the question if it is core or annex.

![image](https://cloud.githubusercontent.com/assets/7791554/6501418/39f0b05a-c353-11e4-8e6e-7ad4056143c1.png)

**Comment by mgeronimo** [comment]
Issue cannot be replicated on our end

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
