### ISSUE TITLE
Newly copied survey is uneditable

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#30]
Steps to replicate:
1. Navigate to the list of surveys.
2. Click copy icon corresponding to an existing survey.

Actual result: Duplication of survey succeeded. However, the duplicate survey has no available icon for edit.
Expected result: The duplicate copy should be considered as draft instead of final.

![image](https://cloud.githubusercontent.com/assets/7791554/6501486/e93b9e26-c353-11e4-9f3e-9b30af53982a.png)

**Comment by xytram** [comment]
Unable to replicate issue.

**Comment by barbacenasmc** [comment]
Issue was verified that it can no longer be replicated.
