### ISSUE TITLE
Error page was displayed when clicked 'Add Sub-office'

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#35]
Steps to replicate:
1. Login as admin to the web app.
2. Navigate to Manage Data page.
3. Click 'Add Sub-office'.

Actual result: Error page was displayed.
Expected result: Add sub-office form should display.

![image](https://cloud.githubusercontent.com/assets/7791554/6539893/57fa3c26-c4be-11e4-80ab-40d9ec929688.png)

**Comment by xytram** [comment]
Cannot replicate issue. Refer to commit #https://github.com/mgeronimo/IOM-DTM/commit/65178ba56010446b34a6f8e022fe6f32bb4d9dba

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
