### ISSUE TITLE
Edit Agency: Agency name field only allows 45 characters

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#40]
Steps to replicate:
1. Navigate to "Manage Data" page.
2. Switch to agencies tab.
3. Select edit icon corresponding to an agency.
4. Copy and paste 255 characters on agency name field.

Actual result: Agency name field only allows 45 characters.
Expected result: Agency name field should allow 255 characters.

![image](https://cloud.githubusercontent.com/assets/7791554/6570156/99bcd9ce-c730-11e4-8073-47ca49c8e531.png)

**Comment by mgeronimo** [comment]
Can this issue be closed now since there will be no module for agency management anymore?
