### ISSUE TITLE
Add New Site: Error page was displayed when added a site with site name only

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#44]
Steps to replicate:
1. Navigate to "Manage Data" page.
2. Click "Add" button on the upper-right corner of the page.
3. Select "New Site".
4. Enter a site name but skip selecting a region, province, municipality and barangay.
5. Click "Save".

Actual result: Error page was displayed and manage data can no longer be accessed because the same error page displays.
Expected result: Addition of new site should not succeed and a validation message should display on required fields.

![image](https://cloud.githubusercontent.com/assets/7791554/6571690/21d6b4f0-c746-11e4-9d8a-210e43b369a8.png)

**Comment by xytram** [comment]
Cannot replicate issue with the current build. Validation is working.

**Comment by barbacenasmc** [comment]
Issue was verified that it can no longer be replicated.
