### ISSUE TITLE
Register Account: Sub-office field disappears after page reloads due to incomplete registration details

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#45]
Steps to replicate:
1. Navigate to register page of web app.
2. Fill-out the form but skip a required field.
3. Select IOM as agency to make the sub-office field display.
4. Select a sub-office and a role.
5. Click "Register" button.

Actual result: Page reloads and validation message was displayed on the skipped required field but the sub-office field disappeared.

Expected result: Sub-office field should still display after reload.

**Before:**
![image](https://cloud.githubusercontent.com/assets/7791554/6590958/e7d5a370-c7f3-11e4-8f4b-41577c502717.png)

**After:**
![image](https://cloud.githubusercontent.com/assets/7791554/6590949/d258fe2a-c7f3-11e4-8270-28657900e01b.png)

**Comment by mgeronimo** [comment]
Issue cannot be replicated.
