### ISSUE TITLE
Register Account: 'Report Viewers' should be 'Reports Viewer'

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#46]
Steps to replicate:
1. Navigate to register user page.
2. Click the dropdown list for user roles.

Actual result: Options were 'Administrator', 'Data Collector' and 'Report Viewers'.
Expected result: 'Report Viewers' should be 'Reports Viewer'
![image](https://cloud.githubusercontent.com/assets/7791554/6591243/bd5d3e10-c7f7-11e4-98ac-f2de3607dfe5.png)

**Comment by mgeronimo** [comment]
Changed it to 'Report Viewer'.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
