### ISSUE TITLE
Register Account: Inconsistent validation for invalid email inputs

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#51]
1. Navigate to the registration page.
2. Fill-out the form correctly. Enter each of the following samples on email address field one at a time.
Abc.example.com

A@b@c@example.com

just"not"right@example.com

this is"not\allowed@example.com

this\ still\"not\\allowed@example.com

john..doe@example.com

john.doe@example..com

Actual result: An inline validation message was displayed for  john..doe@example.com while the rest triggers a pop-up validation message.
Expected result: There should be a consistent way of displaying validation message for invalid email inputs.

![register-invalid-email-20150312](https://cloud.githubusercontent.com/assets/7791554/6611421/d5a94d42-c8a6-11e4-9229-b83163cb4ff7.png)

![register-invalid-email-pop-up-20150312](https://cloud.githubusercontent.com/assets/7791554/6611437/fb1dea74-c8a6-11e4-8e2b-642e0357a898.png)

**Comment by mgeronimo** [comment]
Issue can no longer be replicated.
