### ISSUE TITLE
Login: IOM reports viewer cannot login

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#52]
Steps to replicate:
1. Login as IOM reports viewer.

Actual result: 
-User login did not succeed.
-A prompt telling "Sorry, but only agency administrators are allowed to access the system." was displayed.

Expected result: User login should succeed.

![iom-reports-viewer-login-20150312](https://cloud.githubusercontent.com/assets/7791554/6611874/3e36f228-c8ad-11e4-953b-09e8e182aff1.JPG)

**Comment by xytram** [comment]
Unable to replicate issue.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
