### ISSUE TITLE
Login: Agency reports viewer cannot login 

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#53]
Steps to replicate:
1. Login as agency reports viewer.

Actual result:
-User login did not succeed.
-A prompt telling "Sorry, but only agency administrators are allowed to access the system." was displayed.

Expected result: User login should succeed.

![agency-reports-viewer-login_20150312](https://cloud.githubusercontent.com/assets/7791554/6611897/abc1703e-c8ad-11e4-8f65-fd72a4d99a81.JPG)

**Comment by xytram** [comment]
Cannot replicate issue.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
