### ISSUE TITLE
Add Category: Leading spaces were not automatically trimmed

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#54]
Steps to replicate:

1. Navigate to the questions page
2. Click add button and select 'New Category'
3. Input a category name with leading spaces
4. Input complete description
5. Click save button
6. On the list of categories, click edit icon corresponding to the previously added category.

Actual results: Leading spaces were not automatically trimmed.
Expected result: Leading spaces should be automatically trimmed.

![image](https://cloud.githubusercontent.com/assets/7791554/6612785/73c41456-c8bd-11e4-8ae4-9dbcb85f9795.png)

**Comment by xytram** [comment]
Unable to replicate issue

**Comment by barbacenasmc** [comment]
Issue was verified that it can no longer be replicated.
