### ISSUE TITLE
Edit Category: Category name field allows 100 characters input

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#57]
Steps to replicate:
1. Navigate to the question page
2. At the categories panel edit any existing category by clicking the edit icon
3. Edit and input a category name with 100 characters
4. Retain the value of the description
5. Click save button

Actual result: Category field allows 100 characters input
Expected result: Category field should only allows 45 characters input

![image](https://cloud.githubusercontent.com/assets/7791554/6612948/65efbfe4-c8c0-11e4-8b4c-36bb1ea18152.png)

**Comment by xytram** [comment]
Please see commit https://github.com/mgeronimo/IOM-DTM/commit/1b4c71e7afe91f8c8c6b0f2a3f02334ad0968f70 for fix

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
