### ISSUE TITLE
Edit Category: Save still succeeded after changing the name into spaces

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#59]
Steps to replicate:

1. Navigate to the question page
2. At the categories panel edit any existing category by clicking the edit icon
3. Edit/Change the value of the category name to white spaces only value
4. Retain the value of the description
5. Click save button

Actual result: Save still succeeded.
Expected result: Validation message should display on the category name field indicating that it is required.
![image](https://cloud.githubusercontent.com/assets/7791554/6613027/842d89ae-c8c1-11e4-9c82-fcb396ad8236.png)

**Comment by xytram** [comment]
Duplicate of issue https://github.com/mgeronimo/IOM-DTM/issues/56

Please see commit https://github.com/mgeronimo/IOM-DTM/commit/64cf6b8dee81c61ee777ece7305ae77fdf3d0820 for fix.

**Comment by xytram** [comment]
Duplicate of issue https://github.com/mgeronimo/IOM-DTM/issues/56

Please see commit https://github.com/mgeronimo/IOM-DTM/commit/64cf6b8dee81c61ee777ece7305ae77fdf3d0820 for fix.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
