### ISSUE TITLE
Delete category: There is no confirmation to delete

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#62]
Steps to replicate:
1. Navigate to the question page
2. At the categories panel delete any existing category.
3. Click the delete icon

Actual result: Category was automatically deleted. There is no prompt asking for user's confirmation to delete.
Expected result: A confirmation message should display asking if the deletion of category will proceed.

![image](https://cloud.githubusercontent.com/assets/7791554/6613136/4e22190e-c8c3-11e4-946b-2b4f4770f04f.png)

**Comment by xytram** [comment]
Unable to replicate issue.

**Comment by barbacenasmc** [comment]
Issue was verified that it can no longer be replicated.
