### ISSUE TITLE
Add Question: Default answer accepts negative number for "Number" data type

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#64]
Steps to replicate:

1. Navigate to questions page.
2. Click the Add button and select Add Question.
3. Fill out all required field.
4. Select Number for data type.
5. Enter a negative number on default answer field.
5. Click Save.

Actual result: Save still succeeded.
Expected result: Validation message should display indicating that default answer for number data type should be zero and positive numbers.

![image](https://cloud.githubusercontent.com/assets/7791554/6613366/a0e5a2e8-c8c6-11e4-9303-
f3574093c1db.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
