### ISSUE TITLE
Add Survey: Core questions still exists on available questions to add to survey

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#65]
Steps to replicate:
1. Navigate to add survey form.
2. Click "Add Element" button at the bottom of the page.
3. Choose a category.

Actual result: Observe that core questions still exists on available questions to add to survey.
Expected result: Questions that were already in the form should no longer be available from the list of questions to add.
![image](https://cloud.githubusercontent.com/assets/7791554/6614505/ef07030e-c8d5-11e4-9740-8925970b5c4e.png)

**Comment by xytram** [comment]
Cannot replicate issue on current build (https://github.com/mgeronimo/IOM-DTM/commit/f4e76f38804da4f61b5c2029a46f670656c1551c)

**Comment by barbacenasmc** [comment]
Issue was verified that it can no longer be replicated.
