### ISSUE TITLE
Add Question: Default answer accepts non-numeric characters for percentage data type

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#71]
Steps to replicate:
1. Navigate to questions page.
2. Click the "Add" button and select "Add Question".
3. Fill out all required field.
4. Select percentage for data type.
5. Enter non-numeric characters for percentage field.
5. Click Save.

Actual result: Saving the question still succeeded.
Expected result: Validation message should display on the default answer field indicating that the default answer should be numeric only.

![image](https://cloud.githubusercontent.com/assets/7791554/6631884/2fb77ffe-c968-11e4-9964-7a8155dfdfcb.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
