### ISSUE TITLE
Site Survey Details: Location related columns display number codes

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#72]
Steps to replicate:
1. Using the mobile app, collect data and upload.
2. Login to the web app and navigate to the list of surveys.
3. Click on the survey with recently uploaded data.

Actual result: Location related columns display number codes
Expected result: Location related columns should display the corresponding name of the number codes that it represent.

![image](https://cloud.githubusercontent.com/assets/7791554/6631916/d855fc58-c968-11e4-8562-ebc1da745754.png)

**Comment by mgeronimo** [comment]
This has already been resolved. Please check.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
