### ISSUE TITLE
Add Site: Regions are included '<' and '>' symbols

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#73]
Steps to replicate:
1. Navigate to manage data page.
2. Click "Add" button and select "New Site".
3. On the add site form, click the dropdown list for regions.

Actual result: Regions are included in '<' and '>' symbols 
Expected result: Regions should be displayed without these symbols.

![image](https://cloud.githubusercontent.com/assets/7791554/6632456/aaa4dde8-c971-11e4-8cc8-97175a66e202.png)

**Comment by mgeronimo** [comment]
This has already been resolved. Please check.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
