### ISSUE TITLE
Filter Visual Report: Site which does not belong to the selected barangay still displays

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#75]
Steps to replicate:
1. Navigate to reports.
2. Select a region, province, municipality and barangay.
3. Click "Select Sites" dropdown list.

Actual result: Site which does not belong to the selected barangay still displays
Expected result: Site which does not belong to the selected barangay should not display

![image](https://cloud.githubusercontent.com/assets/7791554/6632746/9ca689d0-c976-11e4-9892-03dcabc196ab.png)

![image](https://cloud.githubusercontent.com/assets/7791554/6632764/d0f42cc4-c976-11e4-813b-8a2f6f629a32.png)

**Comment by mgeronimo** [comment]
This has already been resolved. Please check.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
