### ISSUE TITLE
Register Account: Maxlength of email is 45

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#79]
Steps to replicate:
1. Navigate to register page.
2. Copy and paste an email with 254 characters.
3. Fill-out the rest of the fields.
4. Click "Register".

Actual Result: Email field only allows 45 characters
Expected Result: Email field should allow 254 characters based on generally known standard.

![image](https://cloud.githubusercontent.com/assets/7791554/6680828/871b37b8-cc97-11e4-8be1-0b7ec6b25769.png)
![image](https://cloud.githubusercontent.com/assets/7791554/6680829/8a0b5868-cc97-11e4-8968-3872b01141d4.png)

**Comment by barbacenasmc** [comment]
Only the maxlength on the database was adjusted but the email field on the form still has 45 char maxlength.

![image](https://cloud.githubusercontent.com/assets/7791554/7016269/8d6debb0-dd13-11e4-8e55-41b873c62f60.png)

**Comment by Leirum** [comment]
Issue can still be replicated

![screen shot 2015-04-13 at 11 36 59 am](https://cloud.githubusercontent.com/assets/9795882/7109493/798af800-e1d1-11e4-9eda-7a61d97d4d4d.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
