### ISSUE TITLE
View Visual Report: No prompt to tell that selected site has no available data

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#80]
Steps to replicate:
1. Navigate to reports page.
2. Select a site that is not yet used in any survey.
3. Click "Filter" button.

Actual result: Sections for graph displays blank.
Expected result: There should be a prompt to tell that selected site has no available data.

![image](https://cloud.githubusercontent.com/assets/7791554/6682028/28c021aa-ccac-11e4-983e-f3e54156080a.png)

**Comment by mgeronimo** [comment]
See fix for issue #129

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
