### ISSUE TITLE
Master Templates List: No. of sites column was not updated 

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#83]
Pre-condition:
- A master template with child template already exists
Steps to replicate:

1. Using the mobile app, collect and upload data for the child survey.
2. Login to the web app.
3. Go to "Emergencies".
4. Observe the row of the master template which the previously used child template belongs to.

Actual result: No. of sites was not updated.
Expected result: No. of sites should be updated.
![image](https://cloud.githubusercontent.com/assets/7791554/6746946/74e940d6-cf0c-11e4-981e-e6dc57fda235.png)

**Comment by ramoscharismarie** [comment]
Issue fix was verified.
