### ISSUE TITLE
Reports: Page title should be "Generate Reports"

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#85]
Steps to replicate:
1. Navigate to reports.
2. Click "Generate Report" button on the upper-right corner of the screen.
3. Observe the title of the new page displayed.

Actual result: Title was "Generate PDF Reports"
Expected result: Title should be "Generate Reports" because page is no longer dedicated to generating PDF report but also CSV report.
![generate pdf reports](https://cloud.githubusercontent.com/assets/7791554/6748105/dbd72460-cf1c-11e4-81c4-e932b5d5e615.png)

**Comment by mgeronimo** [comment]
The title now is Generate PDF/CSV Reports. Is that okay?

**Comment by barbacenasmc** [comment]
Yup, that would be better. Thanks! I'm closing this issue now.
