### ISSUE TITLE
Register: Radio button for 'IOM' and 'Others' disappears when page reloads due to a unsuccessful registration

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#91]
Steps to replicate:
1. Navigate to register page.
2. Select 'CCCM' from the list of cluster.
3. Click 'Register' button.

Actual result: After page reloads, the radio button for 'IOM' and 'Others' disappears
Expected result: Radio button for 'IOM' and 'Others' should not disappear after page reloads.

![before](https://cloud.githubusercontent.com/assets/7791554/6889462/2f6c985e-d6c9-11e4-90eb-5469acd35b1e.JPG)

![image](https://cloud.githubusercontent.com/assets/7791554/6889460/29902ea0-d6c9-11e4-86d6-874af62275bc.png)

**Comment by Leirum** [comment]
Issue can still be replicated.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
