### ISSUE TITLE
Register Account: First and last name field accepts inputs greater than their maxlength

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#93]
Steps to replicate:
1. Navigate to the registration page.
2. Copy and paste text on first and last name fields that has greater no. of characters that their maxlength which is 45 characters only.

Actual result: Both fields accept 100 characters.
Expected result: Both fields should only accept 45 characters.

![image](https://cloud.githubusercontent.com/assets/7791554/6889950/9f51be2e-d6d3-11e4-88c3-043310cdb7de.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
