### ISSUE TITLE
Data collector account can login to the web appplication

### ISSUE THREAD

**Issue by barbacenasmc** [mgeronimo/IOM-DTM#97]
Pre-condition:
A data collector account should exist. 

Steps to replicate:
1. Navigate to the login page.
2. Login using the data collector account details.

Actual result: Data collector account was able to login.
Expected result: Datal collector account should not be able to login.

![image](https://cloud.githubusercontent.com/assets/7791554/7016189/10567e7c-dd12-11e4-8982-3f24e2ab92d9.png)

**Comment by mgeronimo** [comment]
Based on what I can recall, they said that data collector can now also login to the web app.

**Comment by barbacenasmc** [comment]
Hi Ms. Madi, if that is the case, what should be the pages that the data collector should access? Should it be exactly the same with the reports viewer? Thus, the system should no longer allow the users to register for a reports viewer + data collector role because data collector role also has the privilege of the reports viewer.

**Comment by mgeronimo** [comment]
So far, it should be the same as with the reports viewer. However, when it comes to the issue of redundancy on the registration, we cannot say yet since I wasn't able to ask them about it. Let retain it for now then just ask them at the meeting tomorrow about their plan regarding it.

**Comment by barbacenasmc** [comment]
Alright, sure. Thanks.
